# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  versioning:
    enabled: true
    resolvers:
      media_type:
        enabled: true
        regex: '/(v|version)=(?P<version>[0-9\.]+)/'
  exception:
    enabled: true
    messages:
      {App\Exception\ResourceValidationException: true}
    codes:
      { App\Exception\ResourceValidationException: 400 }
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: 'force'
    mime_types:
      json: ['application/json', 'application/json;version=1.0']
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: '^/', prefer_extension: true, fallback_format: 'json', priorities: [ 'json' ] }
  param_fetcher_listener: force